name: "go-redis"

on: push

jobs:
  go-redis:
    runs-on: "ubuntu-latest"

    services:
      redis:
        image: "redis"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "Checkout Git Project"
        uses: "actions/checkout@v2"

      - name: "Setup Go Env"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.15.2"

      - name: "Check Go Tests"
        env:
          REDIS_HOST: "redis"
          REDIS_PORT: "6379"
        run: |
          go test ./... --tags redis
